### PR TITLE
Fix position

### PR DESCRIPTION
**Pull request by anteriovieira**

### CODE REVIEW

**Comment by pi0** [comment]
I think it would be better to not overriding default value.

**Comment by anteriovieira** [comment]
@pi0  why closed?

**Comment by pi0** [comment]
@anteriovieira Sorry for not providing enough info. Actually, i've removed all of the default options in this (9fd9b617dcccf6c10076a907be443fce81dda2c4) commit. So this module simply doesn't override any default option of `vue-toasted`.

**Comment by anteriovieira** [comment]
@pi0  I understand, anyway the module documentation (readme) needs to be updated.

**Comment by pi0** [comment]
@anteriovieira If you can make a PR that would be much appreciated. Also if interested in maintaining modules in this repository, i can give you access.

**Comment by slorenzo** [comment]
@pi0 I don't know why this PR was closed, @anteriovieira updated the documentation about how it works. At this moment, the documentation is wrong and the toast isn't seen with `position:center`

**Comment by anteriovieira** [comment]
@pi0 yes, I would like to contribute. I would be happy to have access.

**Comment by pi0** [comment]
@anteriovieira Please accept both and feel free updating docs:

- https://github.com/nuxt-community
- https://github.com/nuxt-community/modules/invitations

Cheers ;)

**Pull request closed without merging**
