### PR TITLE
Optionally disable error handling

### PR DESCRIPTION
**Pull request by silverbackdan**
In relation to issue here: https://github.com/nuxt-community/modules/issues/73

It's be very helpful to simply disable this response interceptor that handles errors. On SSR I'd like to be able to try and refresh a JWT token before displaying a 403 page or whatever custom logic.

I can add documentation if you think this is OK?

### CODE REVIEW

**Comment by pi0** [comment]
@silverbackdan Thanks :) BTW There is another problem remaining for general usage. "Unhandled SSR rejections" However it's okey that adding an option entirely disable error handlers, my suggestion is adding another option just returning error instead of throw rejections. What's your idea?

**Comment by silverbackdan** [comment]
Cool, I'll add some docs in a short while.

Re: "Unhandled SSR rejections" - is there an Issues raised about this one? Just to clarify, is the idea for another option to simply output a nuxt error page as it does at the moment anyway with this error handler on a SSR axios request, but also to make that part optional so that if an option is changed a user can also get a promise error (same as currently on client-side)?

**Comment by silverbackdan** [comment]
Docs added now. Please do mod if you think any minor changes are needed to make any info clearer. Thanks for your quick responses as always @pi0

**Comment by pi0** [comment]
Thanks! I will disable error handler by default too as it seems to be annoying for users using this first time.

**Pull request merged**
