### PR TITLE
google-analytics  - added store as a parameter to the analytics function

### PR DESCRIPTION
**Pull request by awronski**
Usage:
```javascript
export default {
    analytics (from, to, store) {
      const expVar = store.state.visitorId % 3
      return {expId: 12345, expVar}
    },
   [...]
```

### CODE REVIEW

**Comment by pi0** [comment]
LGTM, @awronski would you please add some usage examples to Docs? I've not personally used this any project so have no exact idea to write docs.

**Comment by awronski** [comment]
No problem. i will do it tomorrow.

**Comment by awronski** [comment]
I added the documentation. The analytics in the page works great.

The only problem is still the analytics in the middleware. For example in compliance to EU law I need to anonymize IP. Middleware for it:
```
export default function ({ isServer, route, store }) {
  route.meta.analytics = {
    anonymizeIp: true
  }
}
```

And it is not working for the first request. 

As a workaround I can add analytics to every page, but this solution is not elegant.

**Comment by pi0** [comment]
Nice job so far. We can add initial settings using module options. Will do it and inform you when reached to my laptop 😊

**Comment by awronski** [comment]
But the module options are static, right? What if I want to set userId that I take it from the store?

**Comment by awronski** [comment]
Hi @pi0 , any progress with middleware first request?


Besides that I am thinking to extend it even more, for example to handle [GA events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events)

Eg. tracking what user cliked, like on outbound links or other events (play video, print post etc)

Maybe the best would be something like a GA event bus that we can send events?
What do you think? Any suggestion how to implement it?

**Comment by pi0** [comment]
Hey. Sorry, I was really busy for some core changes. Fixing this is my TDO list. Feel free opening issues for each enhancement so others can discuss and help us :)

**Pull request merged**
