### PR TITLE
frat(toast): add typescript definitions

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
I have add `index.d.ts` to toast module for allow use `this.$toast` in typescript.

Note: This PR is in draft because need this PR : https://github.com/shakee93/vue-toasted/pull/119

Thanks.

### CODE REVIEW

**Comment by pi0** [comment]
Can't wait for it @orblazer :heart_eyes:

**Comment by rossma** [comment]
Would like this feature to be added as well. Waiting to see if the PR gets merged :-)

**Comment by orblazer** [comment]
They is ready for merge ! They just need update vue-toasted to 1.1.27

**Comment by pi0** [comment]
Thanks @orblazer

**Pull request merged**
