### PR TITLE
🔧 upgrade bulma to 0.5.1

### PR DESCRIPTION
**Pull request by acidjazz**

### CODE REVIEW

**Comment by carusog** [comment]
Thanks @acidjazz was just going to fork it for that.
@ghengeveld any chance to get that merged?

**Comment by ghengeveld** [comment]
Would love to but I'm not maintaining this repo 😅

**Comment by pi0** [comment]
Thanks @acidjazz . Will release a new version in few minutes.

@ghengeveld If you are willing to be the lead maintainer for this module, I can provide you needed access and separated official repo.

**Comment by ghengeveld** [comment]
Honestly I'm not using Bulma right now so I have no vetted interest to do so.

**Comment by acidjazz** [comment]
@pi0 I can help maintain this if you'd like

**Comment by carusog** [comment]
@pi0 @acidjazz I'd love to take care of it too. We two can share the effort.

**Pull request merged**
