### PR TITLE
Dynamic API Backend description update

### PR DESCRIPTION
**Pull request by uptownhr**
Simplified description to be more concise.

I'd like to include examples on proxy url changing based on environment. How would this look like?

### CODE REVIEW

**Comment by uptownhr** [comment]
- [ ] Example of proxy url changing based on environment

**Comment by pi0** [comment]
Excellent @uptownhr . Please let me know when PR was ready :)

**Comment by benosman** [comment]
I'd be interested to see an example of how to change the proxy url based on environment.

@uptownhr  @pi0 - any tips on how to do that?

**Comment by uptownhr** [comment]
@benosman example has been updated now.

**Pull request merged**
