### PR TITLE
markdownit: support nuxt v2

### PR DESCRIPTION
**Pull request by dotneet**

### CODE REVIEW

**Comment by syffs** [comment]
IMO, this is not sufficient to support nuxt v2. I think [vue-loader 15](https://github.com/vuejs/vue-loader/tree/v15.0.0-beta.7) deprecated loaders so that they're loaded through webpack.

This does fix `$md`, but for instance [`lang="md"`](https://github.com/nuxt-community/modules/tree/master/packages/markdownit#using-vue-files) does not work anymore

**Comment by dotneet** [comment]
I confirmed that `lang="md"` works in nuxt v2.
Does  this PR not works on your environment?

**Comment by syffs** [comment]
@dotneet indeed, but you may be right about my environment, as your code looks ok to me

**Comment by mohwie** [comment]
Im trying to

**Comment by syffs** [comment]
@pi0 @anteriovieira anything blocking this from being merged?

**Comment by dotneet** [comment]
@anteriovieira Please update npm package.
Nuxt.js 2.0 has been released!

**Comment by pi0** [comment]
Will do it today 😊

**Pull request merged**
