### PR TITLE
feat(google-tag-manager): Allow GTM ID to be function

### PR DESCRIPTION
**Pull request by McSneaky**
This PR allows GTM ID to be function returning String or Promise, as shown in readme.md examples

### CODE REVIEW

**Comment by sowinski** [comment]
@McSneaky, @pi0 
Do you have an idea how to implement dynamic ID's

My website is using different domains for different languages and I also use for each domain a different Google-Tag-Manager account.

**Comment by McSneaky** [comment]
@sowinski Depends if you build it once for all domains or build it separately for each domain?

**Comment by sowinski** [comment]
@McSneaky I build it once.

I use server side rendering and have only one instance for all domains (currently ~25). 

So I am looking for a solution which is doing something like that:

```
export default function({ req }) {

  if (req.headers.referer == "exmple.com")
    return 'GTM-156'
  if (req.headers.referer == "exmple.it")
    return 'GTM-24424'
  if (req.headers.referer == "exmple.es")
    return 'GTM-2424'
 ...
}
```

**Comment by sowinski** [comment]
I think it is not possible without rebuilding the logic of the code.

The module is only called once: https://github.com/nuxt-community/modules/blob/master/packages/google-tag-manager/index.js

It need to be somewhere else.

**Comment by McSneaky** [comment]
Yea, can't use this module's settings.
But you can try to parse it out of head and forceby change it one the fly. 
No idea if it will work or what side effects it might have tho

**Comment by sowinski** [comment]
@McSneaky 
Where would be the best place? I was thinking to rewrite the logic and add it to nuxtServerInit.

What do you think?

**Comment by sowinski** [comment]
@McSneaky 
> But you can try to parse it out of head and forceby change it one the fly.
Can you give me a small example or a hint what you exactly mean?

**Comment by McSneaky** [comment]
> @McSneaky
> 
> > But you can try to parse it out of head and forceby change it one the fly.
> 
> Can you give me a small example or a hint what you exactly mean?

I haven't had change to use Nuxt for ages.. But what I meant is something like this:
```js
// BaseLayout.vue
export default {
  created () {
     if (req.headers.referer == "exmple.com")
       this.head.scripts['gtm'].src = 'https://URL/GTM-156'
     if (req.headers.referer == "exmple.it")
        this.head.scripts['gtm'].src = 'https://URL/GTM-24424' 
  }
}
```
It's a lot of pseudocode and won't work, but hopefully it's enough to get idea going

**Comment by sowinski** [comment]
I changed the implementation a little bit and load the code within nuxtServerInit and it seems to work.

Would be nice if someone could refactore the logic of the  nuxtTagManager within a new function. That way user could reuse the code.

**Pull request merged**
