### PR TITLE
yandex-metrika: fix undefined vars, prevent race condition

### PR DESCRIPTION
**Pull request by IlyaSemenov**
The current yandex-metrika plugin is completely broken, I don't know how it landed in the repository in this shape. Consider the current source code: <https://github.com/nuxt-community/modules/blob/72f0982d6fe85b191941ce3b59f4f909fb355c2e/modules/yandex-metrika/plugin.js>.

In the following code, `w` and `c` are undefined, it will never work:

```js
try {
  (w[c] = w[c] || []).push(function() {
    window['yaCounter<%= options.id %>'] = new Ya.Metrika(<%= JSON.stringify(options) %>);
  })(document, window, 'yandex_metrika_callbacks');
} catch (e) {}
```

This was supposed to be wrapped in `(function (d, w, c) {` (hence the corresponding parameters) but that was lost somehow.

Then, this condition:

```js
  if (!window['Ya'] || window['yaCounter46006413']) {
    console.warn('Yandex metrika is not available')
    return
  }
```

is obviously reversed by mistake (the intent was to fail when `yaCounterXXX` was **not** available).

Now then, even if these both problems are fixed, the plugin suffers from the race condition. It depends on <https://mc.yandex.ru/metrika/watch.js> being executed strictly **after** Nuxt's compiled `app.js` (and picking up `yandex_metrika_callbacks`), which isn't always the case and could be the other way around.

### CODE REVIEW

**Comment by IlyaSemenov** [comment]
I'm also not thrilled by the silencing `try { ... } except {}` caluse, but it's also included in the vendor generated code:

```html
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounterXXX = new Ya.Metrika({
                    id:XXX,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
...
```

So I kept it in place. If it was me I wouldn't silence the initialization.

**Comment by pi0** [comment]
Thanks! i've resolved some merge conflicts. Will local check before release but feel free making PR if anything is wrong with merge

**Comment by IlyaSemenov** [comment]
I don't think this will work:

```js
export default ({ app: { router } }) => {
  ...
  app.router.afterEach(to => {
    ...
```

It should be either `export default ({ app })` (as in was in my version)  or `router.afterEach` (as it used to be before).

**Comment by IlyaSemenov** [comment]
Also, I am inclined to remove the try/catch black. The above issue is just another example why it's bad—it silently omits `ReferenceError: app is not defined` error as if everything was okay.

**Comment by pi0** [comment]
Would you please make a PR for fix? I'm not using yandex for testing

**Comment by IlyaSemenov** [comment]
Absolutely.

**Pull request merged**
