### PR TITLE
- warning about sharing axios instance

### PR DESCRIPTION
**Pull request by awronski**
Warning about sharing axios instance was added to the documentation.

### CODE REVIEW

**Comment by pi0** [comment]
> DO NOT set token or any other user related headers in the SSR phase

Thanks but I'm not sure this statement is 100% correct. nuxtServerInit and server-side Store are isolated for each request. Do you have any reporoducable example of such data leak?

**Comment by awronski** [comment]
I mean to not use the `$axios.setToken` function because it operates on the global axios instance. in the SSR phase. 

Store and nuxtServerInit  is of course isolated.

I will edit the statement.

**Comment by awronski** [comment]
If you don't like the message. - no problem, you can remove it. I just wanted to warn other user. For me it was a surprise.

https://github.com/nuxt-community/modules/issues/89#issuecomment-318165164

But I will appreciate version update and merge because I want to use the request interceptor in production :)

**Comment by pi0** [comment]
@awronski Sorry for delay. That shared problem with `setToken` should be obviously a bug if exists and i try to fix it soon. Meanwhile of transfer axios into a separated repo with some unit tests, I've published `3.1.0` with your enhancement :)

**Pull request closed without merging**
