### PR TITLE
fix html validate error

### PR DESCRIPTION
**Pull request by archieDeveloper**
Bad value true for attribute async on element script.

### CODE REVIEW

**Comment by archieDeveloper** [comment]
nuxt generates such code `<script data-n-head="true" src="https://mc.yandex.ru/metrika/watch.js" async="true"></script>`

now try to check it in [html validator](https://validator.w3.org/nu/#textarea)

```
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
<script data-n-head="true" src="https://mc.yandex.ru/metrika/watch.js" async="true"></script>
</head>
<body>
<p></p>
</body>
</html>
```

result: 
> Error: Bad value true for attribute async on element script.

**Comment by manniL** [comment]
And with your change, it'll be `<script data-n-head="true" src="https://mc.yandex.ru/metrika/watch.js" async></script>`?

**Comment by archieDeveloper** [comment]
@manniL No. It'll be `<script data-n-head="true" src="https://mc.yandex.ru/metrika/watch.js" async=""></script>`
In the official documentation [vue-meta](https://github.com/declandewet/vue-meta) is written about using `undefined` instead of an empty string, but for me it did not work.
The only solution that works is to set the async value to an empty string.
Maybe there is a better solution?

package versions: "nuxt@1.4.1", "vue-meta@1.5.2"

**Comment by manniL** [comment]
@archieDeveloper the latest Nuxt version is `2.3.4` ☺️ 

But good to know that, thanks for the info! Opening an issue in the vue-meta repo wouldn't hurt as well ☺️

**Comment by Ra1nko** [comment]
Now it renders into this
`<script data-n-head="ssr" src="https://mc.yandex.ru/metrika/watch.js"></script>`

Can we get our async back?

**Pull request merged**
